table lab-measurement

	column SampleID
		dataType: string
		summarizeBy: none
		sourceColumn: SampleID

		annotation SummarizationSetBy = Automatic

	column pH
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: pH

		annotation SummarizationSetBy = Automatic

	partition lab-measurement = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MKorb\OneDrive\01 Travel and work\01 MKO Contracting\04 AI stuff\AIprojects\projects\powerbi visuals\visuals\histogram-plus\demo-data\lab-measurement.csv"),[Delimiter=",", Columns=2, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SampleID", type text}, {"pH", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

